package com.clinic.abstracts;

import java.io.Serializable;
import java.lang.reflect.Method;
import java.sql.SQLException;

import com.clinic.Pagination;
import com.clinic.factories.EntityRepositoryFactory;
import com.clinic.interfaces.Copyable;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.SimpleBooleanProperty;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public abstract class AbstractCrudController<T extends AbstractEntity & Copyable<T>, S extends AbstractEntityRepository<T>> {
    public final static int CREATE_ACTION = 1, UPDATE_ACTION = 2, DELETE_ACTION = 3;
    public TableView<T> entityTable;
    public Button createButton;
    public Button updateButton;
    public Button deleteButton;

    private Class<T> entityClass;
    private GridPane formGrid;
    private Scene formScene;
    private Scene mainScene;
    private BooleanProperty selectedItemProperty;
    private T pickResult;

    protected S repo;

    protected AbstractCrudController(Class<T> entityClass, Class<S> repoClass) {
        this.entityClass = entityClass;
        this.repo = EntityRepositoryFactory.getRepository(repoClass);
        this.selectedItemProperty = new SimpleBooleanProperty(true);
        entityTable = new TableView<>();
        initTableViewSchema();
        entityTable.getSelectionModel().selectedItemProperty().addListener(new ChangeListener<T>() {
            @Override
            public void changed(ObservableValue<? extends T> o, T oldVal, T newVal) {
                selectedItemProperty.setValue(newVal == null);
            }
        });
        initMainScene();
        initFormGrid();
        formScene = new Scene(formGrid);
    }

    /**
     * Set the form fields in the grid for creating and updating entities.<br>
     * This method is meant to bind form fields to an <code>entity</code>
     * provided by the method.<br>
     * IMPORTANT: form SHOULD contain submit button generated by the method
     * <code>generateSubmitButton()</code>
     * @param formGrid the form grid for form fields to be placed
     * @param entity the entity that should be binded to the form fields
     */
    protected abstract void setFormGrid(GridPane formGrid, T entity);

    /**
     * Fetch entity data and set it into the table view.
     */
    public void fetchEntitiesToTable() {
        ObservableList<T> entities;
        Pagination page = new Pagination();
        try {
            entities = FXCollections.observableArrayList(repo.get(page));
            entityTable.setItems(entities);
        } catch (SQLException e) {
            System.out.println("Exception caught in AbstractController.fetchEntitiesToTable(): " + e.toString());
        }
    }

    /**
     * Show a table and a pick button to pick an entity from the table
     * @return the selected entity
     */
    public T pickEntity() {
        VBox pickLayout = new VBox();
        pickLayout.setAlignment(Pos.CENTER);
        pickLayout.setSpacing(10.0);
        pickLayout.setPadding(new Insets(20));
        Button pickButton = new Button("Pick");
        pickButton.disableProperty().bind(selectedItemProperty);
        pickLayout.getChildren().addAll(
            pickButton,
            entityTable
        );
        Scene pickScene = new Scene(pickLayout);
        Stage pickStage = new Stage();
        pickButton.setOnAction((event) -> {
            T selectedItem = entityTable.getSelectionModel().getSelectedItem();
            pickResult = getNewEntityInstance(selectedItem.getId()).copy(selectedItem);
            pickStage.close();
        });
        pickStage.setTitle("Pick " + entityClass.getSimpleName());
        pickStage.setScene(pickScene);
        pickStage.showAndWait();
        return pickResult;
    }

    /**
     * Get the main CRUD scene of the controller. <br>
     * WARNING: entity data is not fetched with this method, so you should
     * explicitly call <code>fetchEntitiesToTable()</code>
     * @return scene containing table view and button actions
     */
    public Scene getMainScene() {
        return mainScene;
    }

    /**
     * Show a stage to create an entity
     */
    public void showCreateForm() {
        showForm(CREATE_ACTION);
    }

    /**
     * Show a stage to update an entity
     */
    public void showUpdateForm() {
        showForm(UPDATE_ACTION);
    }

    /**
     * Show a confirmation dialog to delete an entity
     */
    public void showDeleteForm() {
        Alert confirmation = new Alert(Alert.AlertType.CONFIRMATION, "Delete data?");
        confirmation.showAndWait();
        if (confirmation.getResult() == ButtonType.OK) {
            actEntity(entityTable.getSelectionModel().getSelectedItem(), DELETE_ACTION);
            fetchEntitiesToTable();
        }
    }

    /**
     * Initializes new grid object and show a stage to do entity creation
     * or update.
     * @param action <code>CREATE_ACTION</code> or <code>UPDATE_ACTION</code>
     */
    private void showForm(int action) {
        initFormGrid();
        T entity = action == CREATE_ACTION
        ? getNewEntityInstance(null)
        : getCopyOfSelectedItem();
        setFormGrid(formGrid, entity);
        formScene.setRoot(formGrid);
        Stage formStage = new Stage();
        formStage.setScene(formScene);
        formStage.setTitle(action == CREATE_ACTION ? "Create "
                : "Update " +
                        entityClass.getSimpleName());
        formStage.show();
    }

    /**
     * Generates a button that handle form submission
     * @param text text to be displayed on the button
     * @param entity the entity that should be created or updated
     * @return <code>Button</code> that has handler that handles form submission
     */
    protected Button generateSubmitButton(String text, T entity) {
        Button submitButton = new Button();
        submitButton.setText(text);
        submitButton.setOnAction((event) -> {
            int action = entity.getId() != null ? UPDATE_ACTION : CREATE_ACTION;
            actEntity(entity, action);
            Stage stage = (Stage) submitButton.getScene().getWindow();
            stage.close();
            fetchEntitiesToTable();
        });
        return submitButton;
    }

    /**
     * Do database operation on an entity
     * @param entity entity to be acted upon
     * @param action <code>CREATE_ACTION</code> or <code>UPDATE_ACTION</code> or <code>DELETE_ACTION</code>
     */
    protected void actEntity(T entity, int action) {
        try {
            if (action == CREATE_ACTION)
                repo.create(entity);
            else if (action == UPDATE_ACTION)
                repo.edit(entity);
            else if (action == DELETE_ACTION)
                repo.delete(entity.getId());
            else
                System.out.println("AbstractController.actEntity(): Invalid action");
        } catch (SQLException e) {
            System.out.println("Exception caught in AbstractController.actEntity(): " + e.toString());
        }
    }

    /**
     * Initialize main scene which configures button and adds them along with
     * table view.
     */
    private void initMainScene() {
        createButton = new Button("Create");
        updateButton = new Button("Update");
        deleteButton = new Button("Delete");
        createButton.setOnAction(event -> showCreateForm());
        updateButton.setOnAction(event -> showUpdateForm());
        deleteButton.setOnAction(event -> showDeleteForm());

        updateButton.disableProperty().bind(selectedItemProperty);
        deleteButton.disableProperty().bind(selectedItemProperty);

        HBox buttonLayout = new HBox();
        buttonLayout.setSpacing(5.0);
        buttonLayout.getChildren().addAll(createButton, updateButton, deleteButton);

        VBox sceneLayout = new VBox();
        sceneLayout.setAlignment(Pos.CENTER);
        sceneLayout.setSpacing(10.0);
        sceneLayout.setPadding(new Insets(20));
        sceneLayout.getChildren().addAll(
            new Label(entityClass.getSimpleName()),
            buttonLayout,
            entityTable);
        mainScene = new Scene(sceneLayout);
    }

    /**
     * Initialize the column that the table should display
     */
    private void initTableViewSchema() {
        T entityInstance = getNewEntityInstance(null);
        TableColumn<T, Integer> idColumn = new TableColumn<>("Id");
        idColumn.setCellValueFactory(new PropertyValueFactory<>("id"));
        entityTable.getColumns().add(idColumn);
        for (Method method : repo.getEntityAttributeGetters()) {
            if (method.getName() == "getId"
                    || entityInstance.getTableFieldNames() == null
                    || entityInstance
                            .getTableFieldNames()
                            .contains(repo.normalizeFieldName(method.getName().substring(3)))) {
                TableColumn<T, Serializable> tableColumn = new TableColumn<>(
                        method.getName().substring(3).replaceAll("([a-z])([A-Z])", "$1 $2"));
                tableColumn.setCellValueFactory(new PropertyValueFactory<>(
                        method.getName().substring(3, 4).toLowerCase() +
                                method.getName().substring(4)));
                entityTable.getColumns().add(tableColumn);
            }
        }
    }

    /**
     * Get copy of selected item in the table.
     * @return new identical entity object with the selected item.
     */
    private T getCopyOfSelectedItem() {
        T selectedItem = entityTable.getSelectionModel().getSelectedItem();
        try {
            return entityClass
                    .getConstructor(Integer.class)
                    .newInstance(selectedItem.getId())
                    .copy(selectedItem);
        } catch (Exception e) {
            System.out.println("Exception caught in AbstractCrudController.getCopyOfSelectedItem(): " + e.toString());
        }
        return null;
    }

    /**
     * Generates new entity instance
     * @param id id of entity
     */
    private T getNewEntityInstance(Integer id) {
        try {
            return entityClass.getConstructor(Integer.class).newInstance(id);
        } catch (Exception e) {
            System.out.println("Exception caught in AbstractCrudController.getNewEntityInstance(): " + e.toString());
        }
        return null;
    }

    /**
     * Set form grid alignments and spaces.
     */
    private void initFormGrid() {
        formGrid = new GridPane();
        formGrid.setAlignment(Pos.CENTER);
        formGrid.setHgap(10);
        formGrid.setVgap(10);
        formGrid.setPadding(new Insets(25));
    }
}
